spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 2
      bindings:
        goodsPricingRequestChannel:
          group: goodsPricingRequest

        goodsPricingResponseChannel:
          group: goodsPricingResponse

        goodsPricingErrorChannel:
          group: goodsPricingError