spring:
  cloud:
    stream:
      bindings:
        goodsPricingRequestChannel:
          group: goodsPricingRequest

        goodsPricingResponseChannel:
          group: goodsPricingResponse

        goodsPricingErrorChannel:
          group: goodsPricingError