#spring:
#  cloud:
#    stream:
#      bindings:
#        reserveGoodsRequestChannel:
#          group: reserveGoodsRequest
#
#        reserveGoodsResponseChannel:
#          group: reserveGoodsResponse
#
#        unReserveGoodsRequestChannel:
#          group: unReserveGoodsRequest
#
#        unReserveGoodsResponseChannel:
#          group: unReserveGoodsResponse