spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 2
      bindings:
        reserveGoodsErrorChannel:
          group: reserveGoodsError

        reserveGoodsRequestChannel:
          group: reserveGoodsRequest

        reserveGoodsResponseChannel:
          group: reserveGoodsResponse

        unReserveGoodsRequestChannel:
          group: unReserveGoodsRequest

        unReserveGoodsResponseChannel:
          group: unReserveGoodsResponse