spring:
  cloud:
    stream:
      bindings:
        reserveGoodsRequestChannel:
          destination: reserveGoodsRequestChannel
          group: reserveGoodsRequest
        reserveGoodsResponseChannel:
          destination: reserveGoodsResponseChannel
          group: reserveGoodsResponse
