spring:
  cloud:
    stream:
      bindings:
        reserveGoodsRequestChannel:
          group: reserveGoodsRequest

        reserveGoodsResponseChannel:
          group: reserveGoodsResponse

        unReserveGoodsRequestChannel:
          group: reserveGoodsRequest

        unReserveGoodsResponseChannel:
          group: reserveGoodsResponse