spring:
  cloud:
    stream:
      bindings:
        reserveGoodsRequestChannel:
          destination: reserveGoodsRequestChannel
          group: reserveGoodsRequest

        reserveGoodsResponseChannel:
          consumer:
            auto-bind-dlq: false
          producer:
            errorChannelEnabled: true
          group: reserveGoodsResponse
