spring:
  cloud:
    stream:
      bindings:
        reserveGoodsErrorChannel:
          group: reserveGoodsError

        reserveGoodsRequestChannel:
          group: reserveGoodsRequest

        reserveGoodsResponseChannel:
          group: reserveGoodsResponse

        unReserveGoodsRequestChannel:
          group: unReserveGoodsRequest

        unReserveGoodsResponseChannel:
          group: unReserveGoodsResponse