server:
  port: 8081

spring:
  cloud:
    stream:
      bindings:
        goodsPricingRequestChannel:
          group: goodsPricingRequest

        goodsPricingResponseChannel:
          group: goodsPricingResponse

        reserveGoodsRequestChannel:
          group: reserveGoodsRequest

        reserveGoodsResponseChannel:
          group: reserveGoodsResponse
  data:
    mongodb:
      database: sales-order