spring:
  cloud:
    stream:
      bindings:
        createSalesOrderRequestChannel:
          group: createSalesOrderRequest

        goodsPricingRequestChannel:
          group: goodsPricingRequest

        goodsPricingResponseChannel:
          group: goodsPricingResponse

        reserveGoodsRequestChannel:
          group: reserveGoodsRequest

        reserveGoodsResponseChannel:
          group: reserveGoodsResponse

        reserveGoodsErrorChannel:
          group: reserveGoodsError
  data:
    mongodb:
      database: sales-order

server:
  port: 8081