version: "3.1"

services:
  kafka:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - zookeeper
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "${MONGO_VOLUME}:/var/lib/mongodb"
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
networks:
  zookeeper:
    driver: bridge